site_name: Simstring docs
site_url: https://icfly2.github.io/simstring/
nav:
    - Home: index.md
    - Measure: measure.md
    - Searcher: searcher.md
    - Database: database.md
    - Features: features.md

theme:
  name: mkdocs
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s

plugins:
- search
- mkdocstrings


# for local instal:
# pip install mkdocs mkdocs mkdocstrings[python]

# for local development and checking cd insto this folder and run:
# mkdocs serve -w ../docs

# build with:
# mkdocs build -d ../docs
